### ISSUE TITLE
PyLib.stopPython() generates a memory core with java 8

### ISSUE THREAD

**Issue by pabloa** [bcdev/jpy#77]
I executed this test with java 1.8.111, Scala 2.11 and jpy 0.9-SNAPSHOT (SHA1 4a8a43c) and it hangs the JVM when the test tries to stop the python engine.

```Scala
import org.jpy.{PyLib, PyModule, PyObject}
import org.junit.Test
import org.junit.Assert._

/**
  * Tests of invoking from java python code.
  */
class PythonInvocationTest {

  def before(): Unit = {
    System.setProperty("jpy.debug", "true")
    System.setProperty("jpy.config", "/usr/local/lib/python2.7/dist-packages/jpyconfig.properties")
    if (!PyLib.isPythonRunning) {
      val pythonPathEnv = System.getenv("PYTHONPATH")
      val morePhythonPath = "/home/pablo/develop/my/python/stuff:/home/pablo/develop/my/other/stuff"
      println(s"$pythonPathEnv:$morePhythonPath")
      PyLib.startPython((pythonPathEnv + ":" + morePhythonPath).split(":").array: _*)
    }
  }

  def after(): Unit = {
    if (PyLib.isPythonRunning) {
      PyLib.stopPython()  // <-- this line hangs the JVM
    }
  }

  @Test
  def executeSomePython(): Unit = {
    before()
    PyLib.execScript("print 'this is from python'")
    after()
  }
}
```

**Comment by voutilad** [comment]
@pabloa I'm curious if you have tried the same logic in plain Java on your machine using the libraries you built from that snapshot of JPY. Are you able to try a similar JUnit case in plain java?

I resolved a similar issue when using Java 8 (see #71) and I'll see if I can reproduce this in Scala on my machine.

**Comment by voutilad** [comment]
I just tried this on my local machine with the latest build of master and it seems to work. It's a slightly different environment (macOS, Python 2.7.13) but it seems to work at its most basic:

```
$scala -classpath "./lib/*"
Welcome to Scala 2.12.1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_112).
Type in expressions for evaluation. Or try :help.

scala> import org.jpy.{PyLib, PyModule, PyObject}
import org.jpy.{PyLib, PyModule, PyObject}

scala>     System.setProperty("jpy.debug", "true")
res0: String = null

scala> System.setProperty("jpy.config", "/Users/dave/src/jpy/build/lib.macosx-10.12-x86_64-2.7/jpyconfig.properties")
res1: String = null

scala> PyLib.startPython()
org.jpy.PyLib: entered static initializer
org.jpy.PyLibConfig: entered static initializer
org.jpy.PyLibConfig: loading configuration file /Users/dave/src/jpy/build/lib.macosx-10.12-x86_64-2.7/jpyconfig.properties
org.jpy.PyLibConfig: exited static initializer
org.jpy.PyLib: DL.dlopen("/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib", DL.RTLD_GLOBAL + DL.RTLD_LAZY
org.jpy.PyLib: System.load("/Users/dave/src/jpy/build/lib.macosx-10.12-x86_64-2.7/jpy.so")
org.jpy.PyLib: exited static initializer
org.jpy.PyLib: Starting Python with 1 extra module path(s):
org.jpy.PyLib:   /Users/dave/src/jpy/build/lib.macosx-10.12-x86_64-2.7
PyLib_startPython: entered: jenv=0x7fca7d0019f8, pyInit=0, JPy_Module=0x0
PyLib_startPython: global Python interpreter information:
  Py_GetProgramName()     = "python"
  Py_GetPrefix()          = "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7"
  Py_GetExecPrefix()      = "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7"
  Py_GetProgramFullPath() = "/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home//bin/java"
  Py_GetPath()            = "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python27.zip:/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7:/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin:/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac:/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages:/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk:/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old:/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload"
  Py_GetPythonHome()      = "(null)"
  Py_GetVersion()         = "2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]"
  Py_GetPlatform()        = "darwin"
  Py_GetCompiler()        = "
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]"
  Py_GetBuildInfo()       = "default, Dec 18 2016, 07:03:39"
PyLib_startPython: exiting: jenv=0x7fca7d0019f8, pyInit=1, JPy_Module=0x10a6e21d8

scala> PyLib.execScript("print('this is from python')")
<console>:13: warning: method execScript in object PyLib is deprecated: see corresponding Javadoc for more information.
       PyLib.execScript("print('this is from python')")
             ^
Java_org_jpy_PyLib_execScript: script='print('this is from python')'
this is from python
res3: Int = 0

scala> PyLib.isPythonRunning
res4: Boolean = true

scala> PyLib.stopPython()
Java_org_jpy_PyLib_stopPython: entered: JPy_Module=0x10a6e21d8
JPy_free: freeing module data...
JPy_free: done freeing module data
Java_org_jpy_PyLib_stopPython: exiting: JPy_Module=0x0

scala> PyLib.isPythonRunning
res6: Boolean = false
```

**Comment by voutilad** [comment]
I also just tested with Scala 2.12.1 and Python 2.7.6 on Ubuntu 14.04.5. My JPY debug details on start:

```
scala> PyLib.startPython()
org.jpy.PyLib: entered static initializer
org.jpy.PyLibConfig: entered static initializer
org.jpy.PyLibConfig: loading configuration file /home/vagrant/jpy/build/lib.linux-x86_64-2.7/jpyconfig.properties
org.jpy.PyLibConfig: exited static initializer
org.jpy.PyLib: DL.dlopen("/usr/lib/x86_64-linux-gnu/libpython2.7.so", DL.RTLD_GLOBAL + DL.RTLD_LAZY
org.jpy.PyLib: System.load("/home/vagrant/jpy/build/lib.linux-x86_64-2.7/jpy.so")
org.jpy.PyLib: exited static initializer
org.jpy.PyLib: Starting Python with 1 extra module path(s):
org.jpy.PyLib:   /home/vagrant/jpy/build/lib.linux-x86_64-2.7
PyLib_startPython: entered: jenv=0x7fa61400a1f8, pyInit=0, JPy_Module=(nil)
PyLib_startPython: global Python interpreter information:
  Py_GetProgramName()     = "python"
  Py_GetPrefix()          = "/usr"
  Py_GetExecPrefix()      = "/usr"
  Py_GetProgramFullPath() = "/usr/bin/python"
  Py_GetPath()            = "/usr/lib/python2.7/:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload"
  Py_GetPythonHome()      = "(null)"
  Py_GetVersion()         = "2.7.6 (default, Oct 26 2016, 20:33:43)
[GCC 4.8.4]"
  Py_GetPlatform()        = "linux2"
  Py_GetCompiler()        = "
[GCC 4.8.4]"
  Py_GetBuildInfo()       = "default, Oct 26 2016, 20:33:43"
PyLib_startPython: exiting: jenv=0x7fa61400a1f8, pyInit=1, JPy_Module=0x7fa6000b54e8
```

**Comment by Treydone** [comment]
Hi, I have the same error on a Windows 7.1 Java 1.8.25 Python 2.7.13 (Anaconda 4.3.0) 64-bit: the PyLib.stopPython() generates a JVM crash with a EXCEPTION_ACCESS_VIOLATION

**Comment by voutilad** [comment]
@Treydone are you building JPY from the master branch or installing from PyPI?

Also, I believe there are some potential issues with versions of Java 8 prior to update 60 according to issue #56.

**Comment by pabloa** [comment]
Hello @voutilad, I used scala 2.11.8
I will update the JVM to the current last one and I will try again.

**Comment by Treydone** [comment]
@voutilad Yes I was using the master branch. I'll give a try tomorrow with a more recent JDK.

**Comment by Treydone** [comment]
@voutilad I've got the same error using the latest JDK (Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13))

**Comment by voutilad** [comment]
@Treydone and @pabloa I'm still struggling to reproduce the same error using the code in the master branch. 

When we fixed some issues with the `PyLib.stopPython()` call, a unit test was introduced called [org.jpy.LifeCycleTest](https://github.com/bcdev/jpy/blob/master/src/test/java/org/jpy/LifeCycleTest.java). You should be able to run it directly via Maven by executing:

```
mvn -Dtest=org.jpy.LifeCycleTest test -Djpy.config=/Users/dave/src/python/jpy/build/lib.macosx-10.12-x86_64-2.7/jpyconfig.properties
```
Replace `/Users/dave/src/python/jpy/build/lib.macosx-10.12-x86_64-2.7/jpyconfig.properties` with the path to your `jpyconfig.properties` from the `build/`directory for JPY.

You should get 1 test run without errors. If it fails, then either you aren't running master (commit has `e20cea6`) or haven't built the Python libs with `python setup.py bdist_wheel`. If you've properly built the libs and it's still failing, it's possibly an issue with JPY and your Python version. In that case, if you have multiple versions installed, I recommend trying again with a Python virtualenv to make sure you can isolate the version.

If this test works, but your code does not, it could be few issues:

- pointing `jpy.jpyLib/jpy.jdlLib`to the wrong or old instances of the JPY libraries.
- using a different Python version/instance than used to build JPY (are you using virtualenvs?)
- something absolutely funky with our inability to get the GIL lock to safely shutdown the interpreter

If it's the GIL lock issue, it could be related to what you're doing with your Python code. In that case it might be worth taking this into a private discussion for a bit to see if we can isolate what could be the cause.

Sorry for the long winded message! I really want to help get to the bottom of this. If your project can be shared publicly, please let me know and I can take a look at how you've implemented JPY.

**Comment by forman** [comment]
It seems, the issue remains merely on Windows. AppVeyor builds still crash with unit-level tests that call `PyLib.startPython()` / `stopPython()` a second time.
